- name: install packages
  yum: name=gcc,zlib-devel,bzip2,bzip2-devel,readline,readline-devel,sqlite,sqlite-devel,openssl,openssl-devel,git
  become: yes

- name: install pyenv
  git:  
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ ansible_user_dir }}/.pyenv"

- name: Modify bash_profile
  lineinfile: 
    dest: "{{ ansible_user_dir }}/.bash_profile"
    state: present
    line: "{{ item }}"
  with_items: 
    -  'export PYENV_ROOT="$HOME/.pyenv"'
    -  'export PATH="$PYENV_ROOT/bin:$PATH"'
    -  'eval "$(pyenv init -)"'

- name: Refresh login shell
  shell: "/bin/bash -l"

- name: Install Python3
  shell: bash -lc "pyenv install {{ python_version }}"

- name: Refresh python version
  shell: bash -lc "pyenv global {{ python_version }}"


